// Code generated by go test ./x/ -update. DO NOT EDIT.

package x

// fieldSurfaces is which surface has been observed to fill which field, measured
// by decoding the committed fixtures in testdata: the syndication tweet and
// profile timeline, the guest GraphQL profile and timeline, and the x.com status
// and profile pages.
//
// It is evidence, not a promise. A field with no surfaces is one no fixture has
// shown filled, which usually means the plane that carries it is not built yet,
// and a surface with no fixture (3, 5, 6, 7) never appears here at all. Surface
// 7 is surface 4 with a session, so it fills at least what 4 does.
var fieldSurfaces = map[string]map[string][]int{
	"tweet": {
		"author":          {1, 2, 4, 8},
		"bookmarks":       {4, 8},
		"conversation_id": {2, 4},
		"created_at":      {1, 2, 4, 8},
		"entities":        {2, 4},
		"impressions":     {4},
		"is_reply":        {2, 4},
		"is_retweet":      {4},
		"lang":            {1, 2, 4},
		"likes":           {1, 2, 4, 8},
		"media":           {2, 4},
		"quotes":          {2, 4, 8},
		"replies":         {1, 2, 4, 8},
		"reply_to":        {2, 4},
		"reply_to_user":   {2, 4},
		"retweeted":       {4},
		"retweets":        {2, 4, 8},
		"source":          {4},
		"text":            {1, 2, 4, 8},
	},
	"user": {
		"created_at":     {2, 4, 8},
		"description":    {2, 4, 8},
		"entities":       {8},
		"followers":      {2, 4, 8},
		"following":      {2, 4, 8},
		"likes":          {2, 4},
		"listed":         {2, 4},
		"location":       {4, 8},
		"media":          {2, 4},
		"name":           {1, 2, 4, 8},
		"pinned_tweet":   {4},
		"profile_banner": {2, 4},
		"profile_image":  {1, 2, 4, 8},
		"rest_id":        {1, 2, 4, 8},
		"tweets":         {2, 4, 8},
		"username":       {1, 2, 4, 8},
		"verified":       {1, 4, 8},
		"verified_type":  {1, 4},
		"website":        {2, 4},
	},
}
