package x

import (
	"reflect"
	"strings"
)

// fields.go is the field census from spec 3003 doc 03 section 12: every field
// of a record, its type, and which surfaces have been seen to fill it.
//
// It is the answer to "does this tool give me the bookmark count" without
// reading the source, and to "why is this field empty" without guessing. The
// names and types come from the structs by reflection, so they cannot drift.
// The surfaces come from fieldSurfaces in fields_gen.go, which is generated by
// running the committed fixtures through the decoders: see fields_test.go.
//
// Generated rather than declared on purpose. A hand-written table of which
// surface fills which field is a claim, and the whole reason doc 01 exists is
// that claims about X go stale. This one is measured.

// Field is one row of the census.
type Field struct {
	Name string // the JSON name, which is also the name `via` uses
	Type string // the Go type, so *int reads as the absent-or-a-number it is
	// Surfaces that have been observed to fill it, in order. Empty means no
	// fixture has ever shown it filled, which is a weaker statement than "never".
	Surfaces []int
}

// Tier is the cheapest tier that can reach any surface filling this field, and
// false when no surface has been seen to fill it at all.
func (f Field) Tier() (int, bool) {
	best, ok := 0, false
	for _, n := range f.Surfaces {
		t := surfaceTier(n)
		if !ok || t < best {
			best, ok = t, true
		}
	}
	return best, ok
}

// FieldKinds is what `x fields` accepts, in the order it lists them.
var FieldKinds = []string{KindTweet, KindUser}

// Fields is the census for a kind, in declaration order, or nil for a kind that
// has no record type.
func Fields(kind string) []Field {
	var t reflect.Type
	switch kind {
	case KindTweet:
		t = reflect.TypeOf(Tweet{})
	case KindUser:
		t = reflect.TypeOf(User{})
	default:
		return nil
	}
	seen := fieldSurfaces[kind]
	var out []Field
	for _, f := range censusFields(t) {
		f.Surfaces = seen[f.Name]
		out = append(out, f)
	}
	return out
}

// censusFields walks a record type into rows. Meta is skipped: the envelope is
// filled by the fetch, not by a decoder, so "which surface fills url" is not a
// question about the surface's payload. Metrics is expanded in place, because a
// row saying `metrics struct` answers nothing, and because the flat names are
// the ones `via` already uses.
func censusFields(t reflect.Type) []Field {
	var out []Field
	for i := range t.NumField() {
		f := t.Field(i)
		if f.Anonymous && f.Type == reflect.TypeOf(Meta{}) {
			continue
		}
		name, _, _ := strings.Cut(f.Tag.Get("json"), ",")
		if name == "" || name == "-" {
			continue
		}
		if f.Type.Kind() == reflect.Struct && strings.HasSuffix(f.Type.Name(), "Metrics") {
			out = append(out, censusFields(f.Type)...)
			continue
		}
		out = append(out, Field{Name: name, Type: goType(f.Type)})
	}
	return out
}

// goType is the type as it would be written in Go, short enough for a column.
func goType(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Pointer:
		return "*" + goType(t.Elem())
	case reflect.Slice:
		return "[]" + goType(t.Elem())
	}
	if n := t.Name(); n != "" {
		return n
	}
	return t.String()
}

// SurfacesUpTo is the surfaces in ns a given tier can reach. It is here rather
// than in the CLI because surfaceTier is the same table the client routes on,
// and a second copy of "which surface costs what" is a second thing to keep
// right.
func SurfacesUpTo(ns []int, tier int) []int {
	var out []int
	for _, n := range ns {
		if surfaceTier(n) <= tier {
			out = append(out, n)
		}
	}
	return out
}
